// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClEfoT_1vPMqIPsCKQNja70VGrBOZ0uL4',
    appId: '1:62673232322:web:6883ebea9da0b32f00f65b',
    messagingSenderId: '62673232322',
    projectId: 'auth-flutter-541ac',
    authDomain: 'auth-flutter-541ac.firebaseapp.com',
    storageBucket: 'auth-flutter-541ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMSLvqhZz4XyyboMfVBo-JFImUAIkljTI',
    appId: '1:62673232322:android:e8c16274ba8b7e4500f65b',
    messagingSenderId: '62673232322',
    projectId: 'auth-flutter-541ac',
    storageBucket: 'auth-flutter-541ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4v9D0QnhTc_tZej6dXFtYR82-ANlDz2E',
    appId: '1:62673232322:ios:b32144b590633c5100f65b',
    messagingSenderId: '62673232322',
    projectId: 'auth-flutter-541ac',
    storageBucket: 'auth-flutter-541ac.appspot.com',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4v9D0QnhTc_tZej6dXFtYR82-ANlDz2E',
    appId: '1:62673232322:ios:b32144b590633c5100f65b',
    messagingSenderId: '62673232322',
    projectId: 'auth-flutter-541ac',
    storageBucket: 'auth-flutter-541ac.appspot.com',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClEfoT_1vPMqIPsCKQNja70VGrBOZ0uL4',
    appId: '1:62673232322:web:175e0a7c331730c700f65b',
    messagingSenderId: '62673232322',
    projectId: 'auth-flutter-541ac',
    authDomain: 'auth-flutter-541ac.firebaseapp.com',
    storageBucket: 'auth-flutter-541ac.appspot.com',
  );
}
